@extends('layouts.app')
@section('content')
<!DOCTYPE HTML>
<head>
    <meta chrset="UTF-8">
    <html lang="ja"/>
    <title>Template Detail</title>
</head>
<body>
    <h2>タイトル</h2>
        <p>{{$template_title_body->title}}</p>
    <h2>説明</h2>
        <p>{{$template_title_body->body}}</p>
    <h2>必要な材料</h2>
        <details>
            <summary>炭水化物（パン類・穀類・麺類）</summary>
                <h2>パン類</h2>
                    <a>食パン</a>
                    <a>{{$template_carbohydrates_bread->plain_bread}}</a><br>
                    <a>コッペパン</a>
                    <a>{{$template_carbohydrates_bread->koppe_bread}}</a><br>
                    <a>クロワッサン</a>
                    <a>{{$template_carbohydrates_bread->croissant}}</a><br>
                    <a>ロールパン</a>
                    <a>{{$template_carbohydrates_bread->bread_roll}}</a><br>
                    <a>ベーグル</a>
                    <a>{{$template_carbohydrates_bread->bagel}}</a><br>
                    <a>デニッシュ</a>
                    <a>{{$template_carbohydrates_bread->danish}}</a><br>
                    <a>スコーン</a>
                    <a>{{$template_carbohydrates_bread->scone}}</a><br>
                    <a>バゲット</a>
                    <a>{{$template_carbohydrates_bread->baguette}}</a><br>
                    <a>バタール</a>
                    <a>{{$template_carbohydrates_bread->batal}}</a><br>
                    <a>ナン</a>
                    <a>{{$template_carbohydrates_bread->naan}}</a><br>
                    <a>グリッシーニ</a>
                    <a>{{$template_carbohydrates_bread->grissini}}</a><br>
                    <a>マフィン</a>
                    <a>{{$template_carbohydrates_bread->muffin}}</a><br>
                <h2>穀類</h2>
                    <a>米</a>
                    <a>{{$template_carbohydrates_cereals->rice}}</a><br>
                    <a>玄米</a>
                    <a>{{$template_carbohydrates_cereals->brown_rice}}</a><br>
                    <a>雑穀・麦</a>
                    <a>{{$template_carbohydrates_cereals->millet}}</a><br>
                    <a>もち米</a>
                    <a>{{$template_carbohydrates_cereals->sticky_rice}}</a><br>
                    <a>餅</a>
                    <a>{{$template_carbohydrates_cereals->rice_cake}}</a><br>
                    <a>餅巾着</a>
                    <a>{{$template_carbohydrates_cereals->mochikinchaku}}</a><br>
                    <a>シリアル</a>
                    <a>{{$template_carbohydrates_cereals->cereal}}</a><br>
                <h2>麺類</h2>
                    <a>うどん</a>
                    <a>{{$template_carbohydrates_noodles->udon}}</a><br>
                    <a>そうめん</a>
                    <a>{{$template_carbohydrates_noodles->somen}}</a><br>
                    <a>そば</a>
                    <a>{{$template_carbohydrates_noodles->soba}}</a><br>
                    <a>パスタ</a>
                    <a>{{$template_carbohydrates_noodles->pasta}}</a><br>
                    <a>ラーメン</a>
                    <a>{{$template_carbohydrates_noodles->ramen}}</a><br>
                    <a>焼きそば</a>
                    <a>{{$template_carbohydrates_noodles->fried_noodle}}</a><br>
                    <a>つけ麺</a>
                    <a>{{$template_carbohydrates_noodles->tsukemen}}</a><br>
                    <a>冷や麦</a>
                    <a>{{$template_carbohydrates_noodles->hiyamugi}}</a><br>
                    <a>冷麺</a>
                    <a>{{$template_carbohydrates_noodles->cold_noodle}}</a><br>
        </details>
        <details>
            <summary>野菜類</summary>
                    <a>アスパラガス</a>
                    <a>{{$template_vegetable->asparagus}}</a><br>
                    <a>かぼちゃ</a>
                    <a>{{$template_vegetable->pumpkin}}</a><br>
                    <a>キャベツ</a>
                    <a>{{$template_vegetable->cabbage}}</a><br>
                    <a>ごぼう</a>
                    <a>{{$template_vegetable->burdock}}</a><br>
                    <a>サツマイモ</a>
                    <a>{{$template_vegetable->satsumaimo}}</a><br>
                    <a>山菜</a>
                    <a>{{$template_vegetable->sansai}}</a><br>
                    <a>じゃがいも</a>
                    <a>{{$template_vegetable->potato}}</a><br>
                    <a>春菊</a>
                    <a>{{$template_vegetable->crowndaisy}}</a><br>
                    <a>しょうが</a>
                    <a>{{$template_vegetable->garlic}}</a><br>
                    <a>セロリ</a>
                    <a>{{$template_vegetable->celery}}</a><br>
                    <a>大根</a>
                    <a>{{$template_vegetable->daikon}}</a><br>
                    <a>たけのこ</a>
                    <a>{{$template_vegetable->banboo_shoots}}</a><br>
                    <a>たまねぎ</a>
                    <a>{{$template_vegetable->onion}}</a><br>
                    <a>豆苗</a>
                    <a>{{$template_vegetable->been_seedlings}}</a><br>
                    <a>とうもろこし</a>
                    <a>{{$template_vegetable->corn}}</a><br>
                    <a>トマト</a>
                    <a>{{$template_vegetable->tomato}}</a><br>
                    <a>なす</a>
                    <a>{{$template_vegetable->eggplant}}</a><br>
                    <a>にんじん</a>
                    <a>{{$template_vegetable->carrot}}</a><br>
                    <a>ネギ</a>
                    <a>{{$template_vegetable->green_onion}}</a><br>
                    <a>白菜</a>
                    <a>{{$template_vegetable->chinese_cabbage}}</a><br>
                    <a>ピーマン</a>
                    <a>{{$template_vegetable->green_pepper}}</a><br>
                    <a>ブロッコリー</a>
                    <a>{{$template_vegetable->broccoli}}</a><br>
                    <a>らっきょう</a>
                    <a>{{$template_vegetable->rakkyo}}</a><br>
                    <a>レタス</a>
                    <a>{{$template_vegetable->lettuce}}</a><br>
                    <a>レンコン</a>
                    <a>{{$template_vegetable->lotus_root}}</a><br>
                <h2>キノコ類</h2>
                    <a>エノキタケ（赤）</a>
                    <a>{{$template_mushroom->enokitake_red}}</a><br>
                    <a>エノキタケ（茶）</a>
                    <a>{{$template_mushroom->enokitake_brown}}</a><br>
                    <a>ブナシメジ（茶）</a>
                    <a>{{$template_mushroom->bunashimeji_brown}}</a><br>
                    <a>ブナシメジ（白）</a>
                    <a>{{$template_mushroom->bunashimeji_white}}</a><br>
                    <a>シイタケ</a>
                    <a>{{$template_mushroom->shitake}}</a><br>
                    <a>エリンギ</a>
                    <a>{{$template_mushroom->king_trumpet}}</a><br>
                    <a>マイタケ</a>
                    <a>{{$template_mushroom->maitake}}</a><br>
                    <a>白マイタケ</a>
                    <a>{{$template_mushroom->maitake_white}}</a><br>
                    <a>なめこ</a>
                    <a>{{$template_mushroom->nameko}}</a><br>
                    <a>マッシュルーム</a>
                    <a>{{$template_mushroom->mushroom}}</a><br>
                    <a>ヒラタケ</a>
                    <a>{{$template_mushroom->oyster_mushroom}}</a><br>
                <h2>豆類</h2>
                    <a>枝豆</a>
                    <a>{{$template_bean->edamame}}</a><br>
                    <a>大豆</a>
                    <a>{{$template_bean->soybean}}</a><br>
                    <a>グリーンピース</a>
                    <a>{{$template_bean->greenpeace}}</a><br>
                    <a>そら豆</a>
                    <a>{{$template_bean->broad_bean}}</a><br>
                    <a>落花生</a>
                    <a>{{$template_bean->peanut}}</a><br>
                    <a>エンドウ豆</a>
                    <a>{{$template_bean->endomame}}</a><br>
                    <a>インゲン豆</a>
                    <a>{{$template_bean->green_bean}}</a><br>
        </details>
        <details>
            <summary>魚介類</summary>
                    <a>アジ</a>
                    <a>{{$template_marine_products->horse_mackerel}}</a><br>
                    <a>アナゴ</a>
                    <a>{{$template_marine_products->anago}}</a><br>
                    <a>イカ</a>
                    <a>{{$template_marine_products->squid}}</a><br>
                    <a>いくら</a>
                    <a>{{$template_marine_products->ikura}}</a><br>
                    <a>イワシ</a>
                    <a>{{$template_marine_products->sardine}}</a><br>
                    <a>ウナギ</a>
                    <a>{{$template_marine_products->unagi}}</a><br>
                    <a>ウニ</a>
                    <a>{{$template_marine_products->sea_urchin}}</a><br>
                    <a>かずのこ</a>
                    <a>{{$template_marine_products->herring_roe}}</a><br>
                    <a>カツオ</a>
                    <a>{{$template_marine_products->skipjack}}</a><br>
                    <a>カニ</a>
                    <a>{{$template_marine_products->crab}}</a><br>
                    <a>サーモン</a>
                    <a>{{$template_marine_products->salmon}}</a><br>
                    <a>サバ</a>
                    <a>{{$template_marine_products->mackerel}}</a><br>
                    <a>サンマ</a>
                    <a>{{$template_marine_products->pacific_saury}}</a><br>
                    <a>シシャモ</a>
                    <a>{{$template_marine_products->shishamo}}</a><br>
                    <a>シラス</a>
                    <a>{{$template_marine_products->shirasu}}</a><br>
                    <a>すじこ</a>
                    <a>{{$template_marine_products->sujiko}}</a><br>
                    <a>タイ</a>
                    <a>{{$template_marine_products->sea_bream}}</a><br>
                    <a>タコ</a>
                    <a>{{$template_marine_products->octopus}}</a><br>
                    <a>タラ</a>
                    <a>{{$template_marine_products->cod}}</a><br>
                    <a>たらこ</a>
                    <a>{{$template_marine_products->tarako}}</a><br>
                    <a>ちりめんじゃこ</a>
                    <a>{{$template_marine_products->chirimen}}</a><br>
                    <a>フグ</a>
                    <a>{{$template_marine_products->puffer_fish}}</a><br>
                    <a>ホッケ</a>
                    <a>{{$template_marine_products->hokke}}</a><br>
                    <a>マグロ</a>
                    <a>{{$template_marine_products->tuna}}</a><br>
                    <a>明太子</a>
                    <a>{{$template_marine_products->mentaiko}}</a><br>
                <h2>エビ類</h2>
                    <a>エビ（バナメイエビ）</a>
                    <a>{{$template_shrimp->whiteleg_shrimp}}</a><br>
                    <a>赤エビ</a>
                    <a>{{$template_shrimp->red_shrimp}}</a><br>
                    <a>ブラックタイガー</a>
                    <a>{{$template_shrimp->black_tiger_shrimp}}</a><br>
                    <a>クルマエビ</a>
                    <a>{{$template_shrimp->kurumaebi}}</a><br>
                    <a>ボタンエビ</a>
                    <a>{{$template_shrimp->button_shrimp}}</a><br>
                    <a>甘エビ</a>
                    <a>{{$template_shrimp->sweet_shrimp}}</a><br>
                    <a>芝エビ</a>
                    <a>{{$template_shrimp->shiba_shrimp}}</a><br>
                    <a>桜エビ</a>
                    <a>{{$template_shrimp->sakura_shrimp}}</a><br>
                    <a>伊勢エビ</a>
                    <a>{{$template_shrimp->spiny_lobster}}</a><br>
                    <a>ロブスター</a>
                    <a>{{$template_shrimp->lobster}}</a><br>
                <h2>海藻類</h2>
                    <a>生メカブ</a>
                    <a>{{$template_seaweed->namamekabu}}</a><br>
                    <a>生モズク</a>
                    <a>{{$template_seaweed->namamozuku}}</a><br>
                    <a>生ワカメ</a>
                    <a>{{$template_seaweed->namawakame}}</a><br>
                <h2>貝類</h2>
                    <a>アサリ</a>
                    <a>{{$template_shellfish->asari}}</a><br>
                    <a>牡蠣</a>
                    <a>{{$template_shellfish->oyster}}</a><br>
                    <a>シジミ</a>
                    <a>{{$template_shellfish->shijimi}}</a><br>
                    <a>ハマグリ</a>
                    <a>{{$template_shellfish->hamaguri}}</a><br>
                    <a>ホタテ</a>
                    <a>{{$template_shellfish->scallop}}</a><br>
                    <a>ホンビノス貝</a>
                    <a>{{$template_shellfish->hard_clam}}</a><br>
        </details>
        <details>
            <summary>肉類</summary>
                <h2>牛肉</h2>
                    <a>挽肉</a>
                    <a>{{$template_beef->beef_minced}}</a><br>
                    <a>肩</a>
                    <a>{{$template_beef->beef_shoulder}}</a><br>
                    <a>肩ロース</a>
                    <a>{{$template_beef->beef_boston_butt}}</a><br>
                    <a>リブロース</a>
                    <a>{{$template_beef->beef_ribulose}}</a><br>
                    <a>サーロイン</a>
                    <a>{{$template_beef->beef_sirloin}}</a><br>
                    <a>ヒレ</a>
                    <a>{{$template_beef->beef_fillet}}</a><br>
                    <a>バラ</a>
                    <a>{{$template_beef->beef_ribs}}</a><br>
                    <a>モモ</a>
                    <a>{{$template_beef->beef_thigh}}</a><br>
                    <a>ランプ</a>
                    <a>{{$template_beef->beef_rump}}</a><br>
                    <a>スネ</a>
                    <a>{{$template_beef->beef_shin}}</a><br>
                    <a>ネック</a>
                    <a>{{$template_beef->beef_neck}}</a><br>
                <h2>豚肉</h2>
                    <a>挽肉</a>
                    <a>{{$template_pork->pork_minced}}</a><br>
                    <a>肩</a>
                    <a>{{$template_pork->pork_shoulder}}</a><br>
                    <a>肩ロース</a>
                    <a>{{$template_pork->pork_boston_butt}}</a><br>
                    <a>ロース</a>
                    <a>{{$template_pork->pork_lose}}</a><br>
                    <a>ヒレ</a>
                    <a>{{$template_pork->pork_fillet}}</a><br>
                    <a>バラ</a>
                    <a>{{$template_pork->pork_ribs}}</a><br>
                    <a>モモ</a>
                    <a>{{$template_pork->pork_thigh}}</a><br>
                <h2>鶏肉</h2>
                    <a>ムネ</a>
                    <a>{{$template_chicken->chicken_breast}}</a><br>
                    <a>モモ</a>
                    <a>{{$template_chicken->chicken_thigh}}</a><br>
                    <a>ササミ</a>
                    <a>{{$template_chicken->chicken_scissor}}</a><br>
                    <a>ハツ</a>
                    <a>{{$template_chicken->chicken_heart}}</a><br>
                    <a>レバー</a>
                    <a>{{$template_chicken->chicken_lever}}</a><br>
                    <a>砂肝</a>
                    <a>{{$template_chicken->chicken_sand}}</a><br>
                    <a>手羽</a>
                    <a>{{$template_chicken->chicken_wing}}</a><br>
                    <a>首皮</a>
                    <a>{{$template_chicken->chicken_neck_skin}}</a><br>
                    <a>ヤゲン軟骨</a>
                    <a>{{$template_chicken->chicken_cartilage}}</a><br>
                    <a>テール</a>
                    <a>{{$template_chicken->chicken_tail}}</a><br>
                <h2>羊肉</h2>
                    <a>ロース</a>
                    <a>{{$template_mutton->mutton_lose}}</a><br>
                    <a>肩</a>
                    <a>{{$template_mutton->mutton_shoulder}}</a><br>
                    <a>肩ロース</a>
                    <a>{{$template_mutton->mutton_boston_butt}}</a><br>
                    <a>モモ</a>
                    <a>{{$template_mutton->mutton_thigh}}</a><br>
                    <a>バラ</a>
                    <a>{{$template_mutton->mutton_ribs}}</a><br>
                <h2>その他肉類</h2>
                    <a>カモ肉</a>
                    <a>{{$template_other_meat->duck_meat}}</a><br>
                    <a>シカ肉</a>
                    <a>{{$template_other_meat->venison}}</a><br>
                    <a>七面鳥</a>
                    <a>{{$template_other_meat->turckey}}</a><br>
                    <a>ベーコン</a>
                    <a>{{$template_other_meat->bacon}}</a><br>
                    <a>ハム</a>
                    <a>{{$template_other_meat->ham}}</a><br>
                    <a>ソーセージ</a>
                    <a>{{$template_other_meat->sausage}}</a><br>
        </details>
        <details>
            <summary>卵・チーズ・乳製品</summary>
                    <a>ヨーグルト</a>
                    <a>{{$template_eggmilk->yogurt}}</a><br>
                    <a>牛乳</a>
                    <a>{{$template_eggmilk->milk}}</a><br>
                    <a>生クリーム</a>
                    <a>{{$template_eggmilk->fresh_cream}}</a><br>
                    <a>バター</a>
                    <a>{{$template_eggmilk->butter}}</a><br>
                    <a>マーガリン</a>
                    <a>{{$template_eggmilk->margarine}}</a><br>
                    <a>卵</a>
                    <a>{{$template_eggmilk->egg}}</a><br>
                    <a>ウズラ卵</a>
                    <a>{{$template_eggmilk->quail_egg}}</a><br>
                    <a>ピータン</a>
                    <a>{{$template_eggmilk->century_egg}}</a><br>
                    <a>温泉卵</a>
                    <a>{{$template_eggmilk->hot_spring_egg}}</a><br>
                    <a>燻製卵</a>
                    <a>{{$template_eggmilk->smoked_egg}}</a><br>
                <h2>チーズ類</h2>
                    <a>カマンベール</a>
                    <a>{{$template_cheese->camembert_cheese}}</a><br>
                    <a>クリーム</a>
                    <a>{{$template_cheese->cream_cheese}}</a><br>
                    <a>ゴルゴンゾーラ</a>
                    <a>{{$template_cheese->gorgonzola_cheese}}</a><br>
                    <a>ゴーダ</a>
                    <a>{{$template_cheese->gouda_cheese}}</a><br>
                    <a>チェダー</a>
                    <a>{{$template_cheese->cheddar_cheese}}</a><br>
                    <a>マスカルポーネ</a>
                    <a>{{$template_cheese->mascarpone_cheese}}</a><br>
                    <a>モッツァレラ</a>
                    <a>{{$template_cheese->mozzarella_cheese}}</a><br>
        </details>
        <details>
            <summary>果物類</summary>
                <a>あんず</a>
                <a>{{$template_fruits->apricot}}</a><br>
                <a>イチゴ</a>
                <a>{{$template_fruits->strawberry}}</a><br>
                <a>イチジク</a>
                <a>{{$template_fruits->fig}}</a>
                <a>梅</a>
                <a>{{$template_fruits->plum}}</a><br>
                <a>オレンジ</a>
                <a>{{$template_fruits->orange}}</a><br>
                <a>柿</a>
                <a>{{$template_fruits->persimmon}}</a><br>
                <a>キウイフルーツ</a>
                <a>{{$template_fruits->kiwifruit}}</a><br>
                <a>栗</a>
                <a>{{$template_fruits->chestnut}}</a><br>
                <a>グレープフルーツ</a>
                <a>{{$template_fruits->grapefruit}}</a><br>
                <a>サクランボ</a>
                <a>{{$template_fruits->cherry}}</a><br>
                <a>ザクロ</a>
                <a>{{$template_fruits->pomegranate}}</a><br>
                <a>スイカ</a>
                <a>{{$template_fruits->watermelon}}</a><br>
                <a>ナシ</a>
                <a>{{$template_fruits->japanese_pear}}</a><br>
                <a>洋ナシ</a>
                <a>{{$template_fruits->pear}}</a><br>
                <a>パイナップル</a>
                <a>{{$template_fruits->pineapple}}</a><br>
                <a>バナナ</a>
                <a>{{$template_fruits->banana}}</a><br>
                <a>ビワ</a>
                <a>{{$template_fruits->loquat}}</a><br>
                <a>ブドウ</a>
                <a>{{$template_fruits->grape}}</a><br>
                <a>ブルーベリー</a>
                <a>{{$template_fruits->blueberry}}</a><br>
                <a>その他ベリー類</a>
                <a>{{$template_fruits->other_berries}}</a><br>
                <a>マンゴー</a>
                <a>{{$template_fruits->mango}}</a><br>
                <a>ミカン</a>
                <a>{{$template_fruits->mikan}}</a><br>
                <a>メロン</a>
                <a>{{$template_fruits->melon}}</a><br>
                <a>モモ</a>
                <a>{{$template_fruits->peach}}</a><br>
                <a>リンゴ</a>
                <a>{{$template_fruits->apple}}</a><br>
                <a>レモン</a>
                <a>{{$template_fruits->lemon}}</a><br>
        </details>
        <details>
            <summary>漬物・豆腐・納豆</summary>
                <a>厚揚げ</a>
                <a>{{$template_tohunattopickles->atsuage}}</a><br>
                <a>油揚げ</a>
                <a>{{$template_tohunattopickles->fried_tohu}}</a><br>
                <a>梅干し</a>
                <a>{{$template_tohunattopickles->salted_plum}}</a><br>
                <a>キムチ</a>
                <a>{{$template_tohunattopickles->kimchi}}</a><br>
                <a>こんにゃく</a>
                <a>{{$template_tohunattopickles->konjac}}</a><br>
                <a>ザーサイ</a>
                <a>{{$template_tohunattopickles->zha_cai}}</a><br>
                <a>白滝</a>
                <a>{{$template_tohunattopickles->shirataki}}</a><br>
                <a>たくあん</a>
                <a>{{$template_tohunattopickles->pickled_radish}}</a><br>
                <a>佃煮</a>
                <a>{{$template_tohunattopickles->tsukudani}}</a><br>
                <a>豆腐</a>
                <a>{{$template_tohunattopickles->tohu}}</a><br>
                <a>豆腐よう</a>
                <a>{{$template_tohunattopickles->tohuyou}}</a><br>
                <a>納豆</a>
                <a>{{$template_tohunattopickles->natto}}</a><br>
                <a>生湯葉</a>
                <a>{{$template_tohunattopickles->namayuba}}</a><br>
                <a>メンマ</a>
                <a>{{$template_tohunattopickles->menma}}</a><br>
        </details>
        <details>
            <summary>練り物類</summary>
                <a>かまぼこ</a>
                <a>{{$template_kneaded_material->kamaboko}}</a><br>
                <a>伊達巻き</a>
                <a>{{$template_kneaded_material->datemaki}}</a><br>
                <a>つみれ</a>
                <a>{{$template_kneaded_material->tsumire}}</a><br>
                <a>生ちくわ</a>
                <a>{{$template_kneaded_material->namachikuwa}}</a><br>
                <a>はんぺん</a>
                <a>{{$template_kneaded_material->hanpen}}</a><br>
                <a>焼きちくわ</a>
                <a>{{$template_kneaded_material->yakichikuwa}}</a><br>
        </details>
        <details>
            <summary>粉類</summary>
                <a>お好み焼き粉</a>
                <a>{{$template_powders->okonomiyaki_flour}}</a><br>
                <a>片栗粉</a>
                <a>{{$template_powders->starch}}</a><br>
                <a>唐揚げ粉</a>
                <a>{{$template_powders->fried_chicken_flour}}</a><br>
                <a>小麦粉</a>
                <a>{{$template_powders->flour}}</a><br>
                <a>小麦胚芽</a>
                <a>{{$template_powders->wheat_germ}}</a><br>
                <a>米粉</a>
                <a>{{$template_powders->rice_flour}}</a><br>
                <a>コーンスターチ</a>
                <a>{{$template_powders->cornstarch}}</a><br>
                <a>そば粉</a>
                <a>{{$template_powders->buckwheat_flour}}</a><br>
                <a>たこ焼き粉</a>
                <a>{{$template_powders->takoyaki_flour}}</a><br>
                <a>天ぷら粉</a>
                <a>{{$template_powders->tempura_flour}}</a><br>
                <a>ノンフライ用粉</a>
                <a>{{$template_powders->non_fried_flour}}</a><br>
                <a>パン粉</a>
                <a>{{$template_powders->bread_crumbs}}</a><br>
                <a>ふすま</a>
                <a>{{$template_powders->husuma}}</a><br>
        </details>
        <details>
            <summary>乾物類</summary>
                <a>青のり</a>
                <a>{{$template_dried_material->green_laver}}</a><br>
                <a>味付けのり</a>
                <a>{{$template_dried_material->seasoned_seaweed}}</a><br>
                <a>カツオ節</a>
                <a>{{$template_dried_material->katsuobushi}}</a><br>
                <a>乾燥ひじき</a>
                <a>{{$template_dried_material->dried_hijiki}}</a><br>
                <a>乾燥豆</a>
                <a>{{$template_dried_material->dried_beans}}</a><br>
                <a>乾燥野菜</a>
                <a>{{$template_dried_material->dried_vagetables}}</a><br>
                <a>乾燥湯葉</a>
                <a>{{$template_dried_material->dried_yuba}}</a><br>
                <a>乾燥わかめ</a>
                <a>{{$template_dried_material->dried_seaweed}}</a><br>
                <a>かんぴょう</a>
                <a>{{$template_dried_material->kanpyo}}</a><br>
                <a>きくらげ</a>
                <a>{{$template_dried_material->wood_ear}}</a><br>
                <a>きな粉</a>
                <a>{{$template_dried_material->kinako}}</a><br>
                <a>切り干し大根</a>
                <a>{{$template_dried_material->kiriboshi_daikon}}</a><br>
                <a>くずきり</a>
                <a>{{$template_dried_material->kuzukiri}}</a><br>
                <a>削り節</a>
                <a>{{$template_dried_material->kezuribushi}}</a><br>
                <a>高野豆腐</a>
                <a>{{$template_dried_material->koya_tohu}}</a><br>
                <a>ごま</a>
                <a>{{$template_dried_material->sesame}}</a><br>
                <a>だし昆布</a>
                <a>{{$template_dried_material->dashi_kelp}}</a><br>
                <a>とろろ昆布</a>
                <a>{{$template_dried_material->tororo_kelp}}</a><br>
                <a>煮干し</a>
                <a>{{$template_dried_material->niboshi}}</a><br>
                <a>春雨</a>
                <a>{{$template_dried_material->harusame}}</a><br>
                <a>麩</a>
                <a>{{$template_dried_material->wheat_bran}}</a><br>
                <a>ふりかけ</a>
                <a>{{$template_dried_material->hurikake}}</a><br>
                <a>干しエビ</a>
                <a>{{$template_dried_material->dried_shrimp}}</a><br>
                <a>焼きのり</a>
                <a>{{$template_dried_material->grilled_seaweed}}</a><br>
        </details>
        <details>
            <summary>缶詰・瓶詰</summary>
                <a>缶詰の魚介類</a>
                <a>{{$template_canned_bottled->canned_fish_and_shellfish}}</a><br>
                <a>缶詰のフルーツ類</a>
                <a>{{$template_canned_bottled->canned_fruit}}</a><br>
        </details>
        <details>
            <summary>調味料</summary>
                    <a>ウスターソース</a>
                    <a>{{$template_seasoning->worcestershire_sauce}}</a><br>
                    <a>ケチャップ</a>
                    <a>{{$template_seasoning->ketchup}}</a><br>
                    <a>砂糖</a>
                    <a>{{$template_seasoning->sugar}}</a><br>
                    <a>塩</a>
                    <a>{{$template_seasoning->salt}}</a><br>
                    <a>酢</a>
                    <a>{{$template_seasoning->vinegar}}</a><br>
                    <a>醤油</a>
                    <a>{{$template_seasoning->soy_sauce}}</a><br>
                    <a>だし</a>
                    <a>{{$template_seasoning->dashi}}</a><br>
                    <a>ポン酢</a>
                    <a>{{$template_seasoning->ponzu_sauce}}</a><br>
                    <a>マヨネーズ</a>
                    <a>{{$template_seasoning->mayonnaise}}</a><br>
                    <a>味噌</a>
                    <a>{{$template_seasoning->miso}}</a><br>
                    <a>めんつゆ</a>
                    <a>{{$template_seasoning->noodle_soup}}</a><br>
                <h2>ドレッシング</h2>
                    <a>イタリアン</a>
                    <a>{{$template_dressing->italian_dressing}}</a><br>
                    <a>青じそ</a>
                    <a>{{$template_dressing->green_perilla_dressing}}</a><br>
                    <a>ごま</a>
                    <a>{{$template_dressing->sesame_dressing}}</a><br>
                    <a>シーザー</a>
                    <a>{{$template_dressing->caesar_dressing}}</a><br>
                    <a>醤油</a>
                    <a>{{$template_dressing->soy_sauce_dressing}}</a><br>
                    <a>中華</a>
                    <a>{{$template_dressing->chinese_dressing}}</a><br>
                    <a>フレンチ</a>
                    <a>{{$template_dressing->french_dressing}}</a><br>
                    <a>わさび醤油</a>
                    <a>{{$template_dressing->wasabi_soy_sauce_dressing}}</a><br>
                <h2>薬味</h2>
                    <a>大葉</a>
                    <a>{{$template_yakumi->oba}}</a><br>
                    <a>生姜</a>
                    <a>{{$template_yakumi->ginger}}</a><br>
                    <a>三つ葉</a>
                    <a>{{$template_yakumi->mitsuba}}</a><br>
                    <a>ミョウガ</a>
                    <a>{{$template_yakumi->japanese_ginger}}</a><br>
                    <a>柚子</a>
                    <a>{{$template_yakumi->yuzu}}</a><br>
                    <a>わさび</a>
                    <a>{{$template_yakumi->wasabi}}</a><br>
                <h2>ハーブ</h2>
                    <a>パクチー</a>
                    <a>{{$template_herbs->coriander}}</a><br>
                    <a>バジル</a>
                    <a>{{$template_herbs->basil}}</a><br>
                    <a>パセリ</a>
                    <a>{{$template_herbs->parsley}}</a><br>
                    <a>ルッコラ</a>
                    <a>{{$template_herbs->arugula}}</a><br>
                    <a>レモングラス</a>
                    <a>{{$template_herbs->lemongrass}}</a><br>
                    <a>ローズマリー</a>
                    <a>{{$template_herbs->rosemary}}</a><br>
                <h2>オイル</h2>
                    <a>亜麻仁油</a>
                    <a>{{$template_oil->flaxseed_oil}}</a><br>
                    <a>えごま油</a>
                    <a>{{$template_oil->egoma_oil}}</a><br>
                    <a>オリーブオイル</a>
                    <a>{{$template_oil->olive_oil}}</a><br>
                    <a>ココナッツオイル</a>
                    <a>{{$template_oil->coconut_oil}}</a><br>
                    <a>ごま油</a>
                    <a>{{$template_oil->sesame_oil}}</a><br>
                    <a>コーン油</a>
                    <a>{{$template_oil->corn_oil}}</a><br>
                    <a>サラダ油</a>
                    <a>{{$template_oil->salad_oil}}</a><br>
                    <a>菜種油</a>
                    <a>{{$template_oil->rapeseed_oil}}</a><br>
                <h2>スパイス</h2>
                    <a>ガーリック</a>
                    <a>{{$template_spices->garlic_spice}}</a><br>
                    <a>クミン</a>
                    <a>{{$template_spices->cumin}}</a><br>
                    <a>胡椒</a>
                    <a>{{$template_spices->pepper}}</a><br>
                    <a>七味</a>
                    <a>{{$template_spices->shichimi}}</a><br>
                    <a>シナモン</a>
                    <a>{{$template_spices->cinnamon}}</a><br>
                    <a>ターメリック</a>
                    <a>{{$template_spices->turmeric}}</a><br>
                    <a>唐辛子</a>
                    <a>{{$template_spices->chili}}</a><br>
        </details>
    <a href="/food/menu/search/template/{{Auth::User()->id}}">戻る</a>
</body>
@endsection